# Deployment do Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.4
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "kubeNewsAula2"
          - name: POSTGRES_USER
            value: "adminKubeNews"
          - name: POSTGRES_DB
            value: "kubeNewsDB"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: jkommisar/kube-news:v1
          env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_PASSWORD
            value: "kubeNewsAula2"
          - name: DB_USERNAME
            value: "adminKubeNews"
          - name: DB_DATABASE
            value: "kubeNewsDB"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30101
  type: NodePort
